/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datastructs;

public class LinkList {

    public LinkNode head;

    public LinkList() {
        this.head = null;
    }

    class LinkNode {
        public int value;
        public LinkNode next;

        public LinkNode(int value) {
            this.value = value;
            this.next = null;
        }
    }
}